### ISSUE TITLE
Importação de vínculo sem data fim, mas com remunerações.

### ISSUE THREAD

**Issue by efujit** [Contadoria/CalculosPrevidenciarios#6]
Não está sendo possível extrair o período ou as remunerações com o complemento Cálculos Previdenciários, quando o vínculo (empregado doméstico) não possui Data Fim, mas possui remunerações. Situação relativamente atípica, mas como ocorrência. Exemplo: CNIS NIT 12707345816 CPF 21552610802 (upload na pasta Desenvolvimento)

**Comment by cmlima** [comment]
Acho que Isso tem a ver com a opção que fizemos quanto à data final nesses casos. Será necessário alterar a biblioteca TextParser.

**Comment by efujit** [comment]
Resolvido na versão 14 da biblioteca TextParser.
